// Code generated by zipdoc; DO NOT EDIT.

package gateway

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("GET /_/gateway/healthz", zip.Doc{
		Description: "Reports that the gateway process is running and answering HTTP.\n\nIt deliberately consults NOTHING — not the ZAP node, not a backend peer, not\nthe JWKS cache. A liveness probe that fails when a dependency blinks gets a\nhealthy process restarted and turns one outage into two. The relay degrades\nper-request when a backend is absent (see the lazy picker); it does not stop\nbeing alive.",
		Fields: map[string]string{
			"ProbeOut.service": "Service names the service that answered — always \"gateway\", including on\nthe separate k8s health listener, because the listener is a deployment\ndetail and the service is what the operator asked about.",
			"ProbeOut.status":  "Status is \"ok\" from the liveness probe and \"ready\" from the readiness\nprobe. It is the field a scraper reads when it reads the body at all;\norchestrators read the status code.",
		},
	})
	zip.Describe("GET /_/gateway/readyz", zip.Doc{
		Description: "Reports that the gateway is ready to carry traffic.\n\nSame answer as liveness by construction: the gateway holds no per-tenant\nstate, warms no cache it needs before the first request, and dials its\nbackends lazily on first use — so there is no interval during which the\nprocess is up and not yet ready. Readiness is a SEPARATE door rather than an\nalias because the deployment asks the two questions separately, and the day\nthis service acquires something to warm, the widening happens here and\nnowhere else.",
		Fields: map[string]string{
			"ProbeOut.service": "Service names the service that answered — always \"gateway\", including on\nthe separate k8s health listener, because the listener is a deployment\ndetail and the service is what the operator asked about.",
			"ProbeOut.status":  "Status is \"ok\" from the liveness probe and \"ready\" from the readiness\nprobe. It is the field a scraper reads when it reads the body at all;\norchestrators read the status code.",
		},
	})
	zip.Describe("GET /healthz", zip.Doc{
		Description: "Reports that the gateway process is running and answering HTTP.\n\nIt deliberately consults NOTHING — not the ZAP node, not a backend peer, not\nthe JWKS cache. A liveness probe that fails when a dependency blinks gets a\nhealthy process restarted and turns one outage into two. The relay degrades\nper-request when a backend is absent (see the lazy picker); it does not stop\nbeing alive.",
		Fields: map[string]string{
			"ProbeOut.service": "Service names the service that answered — always \"gateway\", including on\nthe separate k8s health listener, because the listener is a deployment\ndetail and the service is what the operator asked about.",
			"ProbeOut.status":  "Status is \"ok\" from the liveness probe and \"ready\" from the readiness\nprobe. It is the field a scraper reads when it reads the body at all;\norchestrators read the status code.",
		},
	})
	zip.Describe("GET /readyz", zip.Doc{
		Description: "Reports that the gateway is ready to carry traffic.\n\nSame answer as liveness by construction: the gateway holds no per-tenant\nstate, warms no cache it needs before the first request, and dials its\nbackends lazily on first use — so there is no interval during which the\nprocess is up and not yet ready. Readiness is a SEPARATE door rather than an\nalias because the deployment asks the two questions separately, and the day\nthis service acquires something to warm, the widening happens here and\nnowhere else.",
		Fields: map[string]string{
			"ProbeOut.service": "Service names the service that answered — always \"gateway\", including on\nthe separate k8s health listener, because the listener is a deployment\ndetail and the service is what the operator asked about.",
			"ProbeOut.status":  "Status is \"ok\" from the liveness probe and \"ready\" from the readiness\nprobe. It is the field a scraper reads when it reads the body at all;\norchestrators read the status code.",
		},
	})
}
